#INCLUDE<16F887.H>
#FUSES HS
#USE DELAY(CLOCK=10M)

#USE RS232(BAUD=4800,BITS=8,STOP=1,PARITY=N, XMIT=PIN_C6,RCV=PIN_C7)

UNSIGNED INT8 DATA;

#INT_RDA
VOID NGAT_UART()
{
   DATA=GETC(); //NHAN VE MA ASCII
   CLEAR_INTERRUPT(INT_RDA); 
}


VOID MAIN()
{ 
   SET_TRIS_C(0X80);
   //CHO PHEP NGAT
   ENABLE_INTERRUPTS(GLOBAL);
   ENABLE_INTERRUPTS(INT_RDA);
   //SETUP_PWM
   SETUP_TIMER_2(T2_DIV_BY_16,124,1);  //PR2=124 => MAXDUTY=(124+1)X4=500                                     
   SETUP_CCP1(CCP_PWM); //RC2
   SET_TIMER2(0);
   SET_PWM1_DUTY(0); //BAN DAU DUNG DONG CO
   WHILE(TRUE)
   {
      IF     (DATA=='S')   SET_PWM1_DUTY(0);//DUNG DONG CO
      ELSE IF(DATA=='R')   SET_PWM1_DUTY((UNSIGNED INT16)125);//20%
      ELSE IF(DATA=='I')   SET_PWM1_DUTY((UNSIGNED INT16)100);//20%
      ELSE IF(DATA=='E')   SET_PWM1_DUTY((UNSIGNED INT16)250);//50%
      ELSE IF(DATA=='A')   SET_PWM1_DUTY((UNSIGNED INT16)500);//100%
   }
}
